"""user: first_name, last_name and default value error fised

Revision ID: d5650f4857a8
Revises: 08d75999e540
Create Date: 2026-06-24 11:35:16.895473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5650f4857a8'
down_revision: Union[str, Sequence[str], None] = '08d75999e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('users', 'fist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fist_name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
