from sqlalchemy.orm import Session, contains_eager

from app.models import DebtItem, MeterReading, NeighborMeter, Neighbor
from app.enums import DebtOrigin, DebtStatus

# Water tariff. Amounts are held in cents, so Bs. 20 is 2000
FLAT_RATE_LIMIT_M3 = 20
FLAT_RATE_CENTS = 2000
PRICE_PER_M3_CENTS = 100


def calculate_amount(consumption: int) -> int:
  """
  Up to 20 m3 the charge is a flat Bs. 20; above that it is Bs. 1 per m3
  """
  if consumption <= FLAT_RATE_LIMIT_M3:
    return FLAT_RATE_CENTS
  return consumption * PRICE_PER_M3_CENTS


def calculate_consumption(reading: MeterReading) -> int:
  """
  Consumption of the period. Clamped at zero: a replaced or rolled over meter
  can read lower than the previous one, and a negative consumption is not billable
  """
  return max(0, (reading.current_reading or 0) - (reading.previous_reading or 0))


def create_debts_for_readings(db: Session, readings: list[MeterReading]) -> list[DebtItem]:
  """
  Creates one pending debt per reading, with default values. The amount is
  settled later, when the reading is actually recorded
  """
  if len(readings) == 0:
    return []

  debts = [
    DebtItem(
      neighbor_id=reading.meter.neighbor_id,
      meter_reading_id=reading.id,
      origin=DebtOrigin.WATER_CONSUMPTION,
      consumption=0,
      amount=0,
      amount_paid=0,
      status=DebtStatus.PENDING,
    )
    for reading in readings
  ]
  db.add_all(debts)
  db.commit()
  return debts


def sync_debt_for_reading(db: Session, reading: MeterReading) -> DebtItem | None:
  """
  Recomputes consumption and amount from the reading. Called whenever the
  reading changes, so editing a value re-bills it.
  A debt already being paid is left alone: changing what someone owes after
  they paid part of it needs a decision, not a silent overwrite.
  """
  debt = reading.debt_item
  if debt is None:
    debt = DebtItem(
      neighbor_id=reading.meter.neighbor_id,
      meter_reading_id=reading.id,
      origin=DebtOrigin.WATER_CONSUMPTION,
      amount_paid=0,
    )
    db.add(debt)

  if debt.amount_paid and debt.amount_paid > 0:
    return debt

  debt.consumption = calculate_consumption(reading)
  debt.amount = calculate_amount(debt.consumption)
  debt.status = DebtStatus.PENDING
  db.commit()
  db.refresh(debt)
  return debt


def _debts_query(db: Session):
  """
  Base query walking the relationships needed to describe a debt, eagerly so
  the response schema does not fire one query per row
  """
  return db.query(DebtItem).join(
    DebtItem.meter_reading
  ).join(
    MeterReading.meter
  ).join(
    DebtItem.neighbor
  ).options(
    contains_eager(DebtItem.meter_reading).contains_eager(MeterReading.meter),
    contains_eager(DebtItem.neighbor),
  )


def get_debts_by_measure(db: Session, measure_id: int) -> list[DebtItem]:
  """
  Debts generated by a measure, ordered by neighbor
  """
  return _debts_query(db).filter(
    MeterReading.measure_id == measure_id
  ).order_by(Neighbor.last_name, Neighbor.first_name).all()


def get_neighbor_debts(db: Session, neighbor_id: int, only_pending: bool = True) -> list[DebtItem]:
  """
  Debts of a neighbor across every measure
  """
  query = _debts_query(db).filter(DebtItem.neighbor_id == neighbor_id)
  if only_pending:
    query = query.filter(DebtItem.status != DebtStatus.PAID)
  return query.order_by(DebtItem.created_at.desc()).all()
