from sqlalchemy.orm import Session, contains_eager

from app.models import DebtItem, MeterReading, NeighborMeter, Neighbor
from app.enums import DebtOrigin, DebtStatus, MeterReadingStatus
import app.services.neighbor_meters as neighbor_meters

# Water tariff. Amounts are held in cents, so Bs. 20 is 2000
FLAT_RATE_LIMIT_M3 = 20
FLAT_RATE_CENTS = 2000
PRICE_PER_M3_CENTS = 100


def calculate_amount(consumption: int) -> int:
  """
  Up to 20 m3 the charge is a flat Bs. 20; above that it is Bs. 1 per m3
  """
  if consumption <= FLAT_RATE_LIMIT_M3:
    return FLAT_RATE_CENTS
  return consumption * PRICE_PER_M3_CENTS


def calculate_consumption(reading: MeterReading, previous_reading: int) -> int:
  """
  Consumption of the period. The previous value is passed in because it is no
  longer stored on the reading: see neighbor_meters.get_previous_reading_map.

  Clamped at zero: a replaced or rolled over meter can read lower than the
  previous one, and a negative consumption is not billable
  """
  return max(0, (reading.current_reading or 0) - (previous_reading or 0))


def create_debts_for_readings(db: Session, readings: list[MeterReading]) -> list[DebtItem]:
  """
  One debt per reading, created with the readings themselves so every meter of
  every measure leaves a record, whether or not it ends up being read.

  They are born PENDING with nothing billed: a meter that is never read keeps
  its debt on the register to be annulled by hand, which is what leaves the
  decision traceable in an audit.
  """
  if len(readings) == 0:
    return []

  debts = [
    DebtItem(
      neighbor_id=reading.meter.neighbor_id,
      meter_reading_id=reading.id,
      origin=DebtOrigin.WATER_CONSUMPTION,
      consumption=0,
      # Not calculate_amount(0): that is the flat rate, Bs. 20. Nothing is
      # billed until the meter is actually read
      amount=0,
      status=DebtStatus.PENDING,
    )
    for reading in readings
  ]
  db.add_all(debts)
  db.commit()
  return debts


def sync_debt_for_reading(db: Session, reading: MeterReading) -> DebtItem | None:
  """
  Creates the debt the first time the reading is recorded, and re-bills it
  whenever the reading is edited afterwards.
  A debt already settled is left alone: changing what someone owes after they
  paid it needs a decision, not a silent overwrite.
  """
  debt = reading.debt_item
  if debt is None:
    debt = DebtItem(
      neighbor_id=reading.meter.neighbor_id,
      meter_reading_id=reading.id,
      origin=DebtOrigin.WATER_CONSUMPTION,
    )
    db.add(debt)

  # A settled debt is not re-billed, and an annulled one stays annulled: both
  # are decisions that a later edit must not undo silently
  if debt.status in (DebtStatus.PAID, DebtStatus.CANCELLED):
    return debt

  if reading.status != MeterReadingStatus.READED:
    # Still on the record, still owing nothing: calculate_amount(0) would
    # charge the flat rate for a meter nobody read
    debt.consumption = 0
    debt.amount = 0
  else:
    previous_reading = neighbor_meters.get_previous_reading(db, reading)
    debt.consumption = calculate_consumption(reading, previous_reading)
    debt.amount = calculate_amount(debt.consumption)

  debt.status = DebtStatus.PENDING
  db.commit()
  db.refresh(debt)
  return debt


def _debts_query(db: Session):
  """
  Base query walking the relationships needed to describe a debt, eagerly so
  the response schema does not fire one query per row
  """
  return db.query(DebtItem).join(
    DebtItem.meter_reading
  ).join(
    MeterReading.meter
  ).join(
    DebtItem.neighbor
  ).options(
    contains_eager(DebtItem.meter_reading).contains_eager(MeterReading.meter),
    contains_eager(DebtItem.neighbor),
  )


def get_debts_by_measure(db: Session, measure_id: int) -> list[DebtItem]:
  """
  Debts generated by a measure, ordered by neighbor
  """
  return _debts_query(db).filter(
    MeterReading.measure_id == measure_id
  ).order_by(Neighbor.pat_lname, Neighbor.names).all()


def get_neighbor_debts(db: Session, neighbor_id: int, only_pending: bool = True) -> list[DebtItem]:
  """
  Debts of a neighbor across every measure
  """
  query = _debts_query(db).filter(DebtItem.neighbor_id == neighbor_id)
  if only_pending:
    query = query.filter(DebtItem.status != DebtStatus.PAID)
  debts = query.order_by(DebtItem.created_at.desc()).all()

  # The schema reads previous_reading through the reading, and it is derived
  neighbor_meters.annotate_previous_readings(
    db, [debt.meter_reading for debt in debts if debt.meter_reading]
  )
  return debts
